// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.ms');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_ARG = "Add Argument";  // untranslated
Blockly.Msg.ADD_ARGS = "Add Arguments";  // untranslated
Blockly.Msg.ADD_COMMENT = "Berikan Komen";
Blockly.Msg.ANALOG_READ = "analog Read";  // untranslated
Blockly.Msg.ANALOG_WRITE = "analog Write";  // untranslated
Blockly.Msg.ANGLE = " angle";  // untranslated
Blockly.Msg.ARCOIRIS = "Rainbow";  // untranslated
Blockly.Msg.AUTH = "Sila benarkan aplikasi ini untuk membolehkan hasil kerja anda disimpan, malah dikongsikan oleh anda.";
Blockly.Msg.BLACK = "BLACK";  // untranslated
Blockly.Msg.BLINK = "Blink ";  // untranslated
Blockly.Msg.BOOLEAN = "boolean";  // untranslated
Blockly.Msg.BOOLEANO = "Boolean";  // untranslated
Blockly.Msg.BY = "by";  // untranslated
Blockly.Msg.CHANGE_VALUE_TITLE = "Ubah nilai:";
Blockly.Msg.CHAR = "Character";  // untranslated
Blockly.Msg.CHAT = "Bersembang dengan rakan kerjasama anda dengan menaip di dalam petak ini!";
Blockly.Msg.CLEAN_UP = "Clean up Blocks";  // untranslated
Blockly.Msg.CLICKDER = "Right_Click";  // untranslated
Blockly.Msg.CLICKIZQ = "Left_Click";  // untranslated
Blockly.Msg.CLICKMID = "Middle_Click";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "Lipat Blok²";
Blockly.Msg.COLLAPSE_BLOCK = "Lipat Blok";
Blockly.Msg.COLOR = " colour";  // untranslated
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "warna 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "warna 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "nisbah";
Blockly.Msg.COLOUR_BLEND_TITLE = "adun";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Campurkan dua warna sekali pada nisbah yang ditentukan (0.0 - 1.0).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://ms.wikipedia.org/wiki/Warna";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Pilih satu warna daripada palet.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "warna rawak";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Pilih satu warna secara rawak.";
Blockly.Msg.COLOUR_RGB_BLUE = "biru";
Blockly.Msg.COLOUR_RGB_GREEN = "hijau";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "merah";
Blockly.Msg.COLOUR_RGB_TITLE = "warnakan";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Peroleh satu warna dengan menentukan amaun campuran merah, hijau dan biru. Kesemua nilai haruslah antara 0 hingga 100.";
Blockly.Msg.COMENTARIO = "Comment";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "hentikan gelung";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "teruskan dengan lelaran gelung seterusnya";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Keluar dari gelung pengandung.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Langkau seluruh gelung yang tinggal dan bersambung dengan lelaran seterusnya.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Amaran: Blok ini hanya boleh digunakan dalam satu gelung.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "untuk setiap perkara %1 dalam senarai %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Untuk setiap perkara dalam senarai, tetapkan pembolehubah '%1' pada perkara, kemudian lakukan beberapa perintah.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "kira dengan %1 dari %2 hingga %3 selang %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Gunakan pembolehubah \"%1\" pada nilai-nilai dari nombor pangkal hingga nombor hujung, mengira mengikut selang yang ditentukan, dan lakukan blok-blok yang tertentu.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Tambah satu syarat kepada blok jika.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Tambah yang terakhir, alihkan semua keadaan ke blok jika.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Tambah, alih keluar, atau susun semula bahagian-bahagian untuk menyusun semula blok jika.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "lain";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "lain jika";
Blockly.Msg.CONTROLS_IF_MSG_IF = "jika";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Jika nilai yang benar, lakukan beberapa penyata.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Jika suatu nilai benar, lakukan penyata blok pertama.  Jika tidak, bina penyata blok kedua.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Jika nilai yang pertama adalah benar, lakukan penyata pertama blok.  Sebaliknya, jika nilai kedua adalah benar, lakukan penyata blok kedua.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Jika nilai yang pertama adalah benar, lakukan penyata blok pertama.  Sebaliknya, jika nilai kedua adalah benar, lakukan penyata blok kedua.  Jika tiada nilai adalah benar, lakukan penyata blok terakhir.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "lakukan";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "ulang %1 kali";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Lakukan perintah berulang kali.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "ulangi sehingga";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "ulangi apabila";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Lakukan beberapa perintah apabila nilainya palsu (false).";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Lakukan beberapa perintah apabila nilainya benar (true).";
Blockly.Msg.COUNTER = "Counter";  // untranslated
Blockly.Msg.CUMPLEANOS = "Birthday";  // untranslated
Blockly.Msg.DECLARACIONES = "Statements";  // untranslated
Blockly.Msg.DECR_CONT = "Decrement";  // untranslated
Blockly.Msg.DELAY = "Delay";  // untranslated
Blockly.Msg.DELETE_BLOCK = "Hapuskan Blok";
Blockly.Msg.DELETE_X_BLOCKS = "Hapuskan %1 Blok";
Blockly.Msg.DER = "RT";  // untranslated
Blockly.Msg.DIFFERENTTO = "Different to";  // untranslated
Blockly.Msg.DIGITAL_READ = "digital Read";  // untranslated
Blockly.Msg.DIGITAL_WRITE = "digital Write";  // untranslated
Blockly.Msg.DIRECCION = "direction";  // untranslated
Blockly.Msg.DISABLE_BLOCK = "Matikan Blok";
Blockly.Msg.DISTANCE = "distance";  // untranslated
Blockly.Msg.DUPLICATE_BLOCK = "Pendua";
Blockly.Msg.DURACION = "duration";  // untranslated
Blockly.Msg.EJE_X = "axis x";  // untranslated
Blockly.Msg.EJE_Y = "axis y";  // untranslated
Blockly.Msg.ENABLE_BLOCK = "Hidupkan Blok";
Blockly.Msg.EQUALTO = "Equal to";  // untranslated
Blockly.Msg.EXPAND_ALL = "Buka Blok²";
Blockly.Msg.EXPAND_BLOCK = "Buka Blok";
Blockly.Msg.EXTERNAL_INPUTS = "Input Luaran";
Blockly.Msg.FIN_CODE_PYGMO = "       End";  // untranslated
Blockly.Msg.FLOAT = "float";  // untranslated
Blockly.Msg.FOR = "Count with";  // untranslated
Blockly.Msg.FOREVER = "Forever                                  ";  // untranslated
Blockly.Msg.FORWARD = "FORWARD";  // untranslated
Blockly.Msg.FRECUENCY = "frecuency";  // untranslated
Blockly.Msg.FROM = "from";  // untranslated
Blockly.Msg.FUNCTION = "Function";  // untranslated
Blockly.Msg.FUNCTIONWIHTRETURN = "Return Function";  // untranslated
Blockly.Msg.GOFORWARD = "go Forward ";  // untranslated
Blockly.Msg.GOREVERSE = "go Reverse ";  // untranslated
Blockly.Msg.GREATEROREQUAL = "Grater or Equal to";  // untranslated
Blockly.Msg.GREATERTHAN = "Greater than";  // untranslated
Blockly.Msg.HELP = "Bantuan";
Blockly.Msg.HIGH = "HIGH";  // untranslated
Blockly.Msg.INCR_CONT = "Increase";  // untranslated
Blockly.Msg.INICIO_CODE = "Starting program";  // untranslated
Blockly.Msg.INLINE_INPUTS = "Input Sebaris";
Blockly.Msg.INPUT = "INPUT";  // untranslated
Blockly.Msg.INPUT_PULLUP = "INPUT_PULLUP";  // untranslated
Blockly.Msg.INT = "int";  // untranslated
Blockly.Msg.INVERTIR = "Reverse motion";  // untranslated
Blockly.Msg.IZQ = "LFT";  // untranslated
Blockly.Msg.KEYBOARD_BEGIN = "Keyboard begin";  // untranslated
Blockly.Msg.KEYBOARD_PRINT = "Keyboard print";  // untranslated
Blockly.Msg.KEYBOARD_TEXT = "Write one key";  // untranslated
Blockly.Msg.LEDOFF = "LED Off";  // untranslated
Blockly.Msg.LEDON = "LED On";  // untranslated
Blockly.Msg.LENGTH = "length";  // untranslated
Blockly.Msg.LESSOEQUAL = "Less or Equal to";  // untranslated
Blockly.Msg.LESSTHAN = "Less than";  // untranslated
Blockly.Msg.LIBRERIA = "Library";  // untranslated
Blockly.Msg.LIBRERIA_TEXT = "Write the Library'name";  // untranslated
Blockly.Msg.LINEA_CODIGO = "Line Code";  // untranslated
Blockly.Msg.LINECOMPARE = "line Compare";  // untranslated
Blockly.Msg.LINEREAD = "line Read";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "Wujudkan senarai kosong";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Kembalikan senarai panjang 0, yang tidak mengandungi rekod data";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "senarai";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Tambah, alih keluar, atau susun semula bahagian-bahagian untuk menyusun semula senarai blok.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "wujudkan senarai dengan";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Tambah item ke dalam senarai.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Wujudkan senarai dengan apa jua nombor item.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "pertama";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# dari akhir";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "dapatkan";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "dapat dan alihkan";
Blockly.Msg.LISTS_GET_INDEX_LAST = "terakhir";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "rawak";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "alihkan";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Kembalikan item pertama dalam senarai.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Kembalikan item dalam kedudukan yang ditetapkan dalam senarai. #1 ialah item terakhir.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Kembalikan item dalam kedudukan yang ditetapkan dalam senarai. #1 ialah item terakhir.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Kembalikan item pertama dalam senarai.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Kembalikan item rawak dalam senarai.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Alihkan dan kembalikan item pertama dalam senarai.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Alihkan dan kembalikan item mengikut spesifikasi posisi dalam senarai. #1 ialah item terakhir.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Alihkan dan kembalikan item mengikut spesifikasi posisi dalam senarai. #1 ialah item pertama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Alihkan dan kembalikan item terakhir dalam senarai.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Alihkan dan kembalikan item rawak dalam senarai.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Alihkan item pertama dalam senarai.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Alihkan item mengikut spesifikasi posisi dalam senarai. #1 ialah item terakhir.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Alihkan item pada posisi mengikut spesifikasi dalam senarai. #1 ialah item pertama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Alihkan item terakhir dalam senarai.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Alihkan item rawak dalam senarai.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "ke  # dari akhir";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "ke #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "ke akhir";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "dapatkan sub-senarai daripada pertama";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "dapatkan sub-senarai daripada # daripada terakhir";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "dapatkan sub-senarai daripada #";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Wujudkan salinan bahagian yang ditentukan dari senarai.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "cari pertama item kejadian";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "cari kejadian akhir item";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Kembalikan indeks kejadian pertama/terakhir item dalam senarai. Kembalikan 0 jika teks tidak ditemui.";
Blockly.Msg.LISTS_INLIST = "dalam senarai";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 adalah kosong";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Kembalikan benar jika senarai kosong.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "panjang %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Kembalikan panjang senarai";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "wujudkan senarai dengan item %1 diulangi %2 kali";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Wujudkan senarai yang terdiri daripada nilai berulang mengikut nombor yang ditentukan.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "sebagai";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "masukkan pada";
Blockly.Msg.LISTS_SET_INDEX_SET = "set";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Selit item pada permulaan senarai.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Masukkan item pada posisi yang ditentukan dalam senarai. #1 ialah item terakhir.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Masukkan item pada posisi yand ditentukan dalam senarai. #1 ialah item terakhir.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Tambahkan item dalam senarai akhir.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Selit item secara rawak di dalam senarai.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Set item pertama dalam senarai.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Masukkan item pada posisi yang ditentukan dalam senarai. #1 ialah item terakhir.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Masukkan item pada posisi yang ditentukan dalam senarai. #1 ialah item terakhir.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Set item terakhir dalam senarai.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Set item rawak dalam senarai.";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "buat senarai dgn teks";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "buat teks drpd senarai";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Cantumkan senarai teks menjadi satu teks, dipecahkan oleh delimiter.";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Pecahkan teks kepada senarai teks, berpecah di setiap delimiter.";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "dengan delimiter";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "palsu";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Kembalikan samada benar atau palsu.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "benar";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://id.wikipedia.org/wiki/Pertidaksamaan";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Kembali benar jika kedua-dua input benar antara satu sama lain.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Kembali benar jika input pertama adalah lebih besar daripada input kedua.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Kembali benar jika input pertama adalah lebih besar daripada atau sama dengan input kedua.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Kembali benar jika input pertama adalah lebih kecil daripada input kedua.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Kembali benar jika input pertama adalah lebih kecil daripada atau sama dengan input kedua.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Taip balik benar jika kedua-dua input tidak sama.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "bukan %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "'Benar' akan dibalas jika inputnya salah. 'Salah' akan dibalas jika inputnya benar.";
Blockly.Msg.LOGIC_NULL = "null";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Returns null.";
Blockly.Msg.LOGIC_OPERATION_AND = "dan";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "atau";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Return true if both inputs are true.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Return true if at least one of the inputs is true.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "Jika palsu";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "Jika benar";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Check the condition in 'test'. If the condition is true, returns the 'if true' value; otherwise returns the 'if false' value.";
Blockly.Msg.LOOP = "Loop         ";  // untranslated
Blockly.Msg.LOW = "LOW";  // untranslated
Blockly.Msg.LUZ = "light";  // untranslated
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://ms.wikipedia.org/wiki/Aritmetik";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Kembalikan jumlah kedua-dua bilangan.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Taip balik hasil bahagi dua nombor tersebut.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Taip balik hasil tolak dua nombor tersebut.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Taip balik hasil darab dua nombor tersebut.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Return the first number raised to the power of the second number.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://id.wikipedia.org/wiki/Perjumlahan";
Blockly.Msg.MATH_CHANGE_TITLE = "perubahan %1 oleh %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Tambah nombor kepada pembolehubah '%1'.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://ms.wikipedia.org/wiki/Pemalar_matematik";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Return one of the common constants: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "constrain %1 low %2 high %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Constrain a number to be between the specified limits (inclusive).";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "Boleh dibahagikan dengan";
Blockly.Msg.MATH_IS_EVEN = "Adalah genap";
Blockly.Msg.MATH_IS_NEGATIVE = "negatif";
Blockly.Msg.MATH_IS_ODD = "aneh";
Blockly.Msg.MATH_IS_POSITIVE = "adalah positif";
Blockly.Msg.MATH_IS_PRIME = "is prime";
Blockly.Msg.MATH_IS_TOOLTIP = "Check if a number is an even, odd, prime, whole, positive, negative, or if it is divisible by certain number.  Returns true or false.";
Blockly.Msg.MATH_IS_WHOLE = "is whole";
Blockly.Msg.MATH_MODULO_HELPURL = "https://id.wikipedia.org/wiki/Operasi_modulus";
Blockly.Msg.MATH_MODULO_TITLE = "remainder of %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Taip balik baki yang didapat daripada pembahagian dua nombor tersebut.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";
Blockly.Msg.MATH_NUMBER_HELPURL = "https://ms.wikipedia.org/wiki/Nombor";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Suatu nombor.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "purata daripada senarai";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "Max senarai";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "Median senarai";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "min dalam senarai";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "jenis senarai";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "Item rawak daripada senarai";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "sisihan piawai bagi senarai";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "Jumlah senarai";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Kembalikan purata (min aritmetik) nilai-nilai angka di dalam senarai.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Pulangkan jumlah terbesar dalam senarai.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Kembalikan nombor median dalam senarai.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Kembalikan nombor terkecil dalam senarai.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Kembali senarai item yang paling biasa dalam senarai.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Kembalikan elemen rawak daripada senarai.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Kembali dengan sisihan piawai daripada senarai.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Kembalikan jumlah semua nombor dalam senarai.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "pecahan rawak";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Kembali sebahagian kecil rawak antara 0.0 (inklusif) dan 1.0 (eksklusif).";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "integer rawak dari %1ke %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Kembalikan integer rawak diantara dua had yang ditentukan, inklusif.";
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "pusingan";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "Pusingan ke bawah";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "pusingan ke atas";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Bulat nombor yang naik atau turun.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://ms.wikipedia.org/wiki/Punca_kuasa_dua";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "mutlak";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "Punca kuasa dua";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Kembalikan nilai mutlak suatu nombor.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Kembalikan e kepada kuasa nombor.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Kembali dalam logaritma nombor asli.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Kembali logarithm 10 asas nombor.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Kembalikan nombor yang songsang.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Kembalikan 10 kepada kuasa nombor.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Kembalikan punca kuasa nombor.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";
Blockly.Msg.MATH_TRIG_ACOS = "acos";
Blockly.Msg.MATH_TRIG_ASIN = "asin";
Blockly.Msg.MATH_TRIG_ATAN = "atan";
Blockly.Msg.MATH_TRIG_COS = "cos";
Blockly.Msg.MATH_TRIG_HELPURL = "https://ms.wikipedia.org/wiki/Fungsi_trigonometri";
Blockly.Msg.MATH_TRIG_SIN = "sin";
Blockly.Msg.MATH_TRIG_TAN = "tan";
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Kembali arccosine beberapa nombor.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Kembalikan arcsince beberapa nombor.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Kembalikan beberapa nombor arctangent.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Kembalikan darjah kosinus (bukan radian).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Kembalikan darjah sine (bukan radian).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Kembalikan darjah tangen (bukan radian).";
Blockly.Msg.ME = "Saya";
Blockly.Msg.MICROSEGUNDOS = "microseconds";  // untranslated
Blockly.Msg.MILISEGUNDOS = "miliseconds";  // untranslated
Blockly.Msg.MILLIS = "Elapsed milliseconds";  // untranslated
Blockly.Msg.MODE = "mode";  // untranslated
Blockly.Msg.MOTORS_OFF = "motors Off ";  // untranslated
Blockly.Msg.MOTOR_OFF = "motor Off";  // untranslated
Blockly.Msg.MOTOR_ON = "motor On";  // untranslated
Blockly.Msg.MOTOR_SPEED = "motor Speed";  // untranslated
Blockly.Msg.MOUSE_BEGIN = "Mouse begin";  // untranslated
Blockly.Msg.MOUSE_MOVE = "Mouse move";  // untranslated
Blockly.Msg.NAMEINIT = "name";  // untranslated
Blockly.Msg.NAVIDAD = "Christmas";  // untranslated
Blockly.Msg.NEW_VARIABLE = "Pembolehubah baru...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Nama pembolehubah baru:";
Blockly.Msg.NOTA = "note";  // untranslated
Blockly.Msg.NO_TONE = "No tone";  // untranslated
Blockly.Msg.NUMERIC = "Number";  // untranslated
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.OUTPUT = "OUTPUT";  // untranslated
Blockly.Msg.OWNCODE = "Write your own code";  // untranslated
Blockly.Msg.PINMODE = "pin Mode";  // untranslated
Blockly.Msg.PIROGAMES = "Pyrotechnic Games";  // untranslated
Blockly.Msg.POLICIA = "Police";  // untranslated
Blockly.Msg.PORT = " port";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "bolehkan kenyataan";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "dengan:";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://ms.wikipedia.org/wiki/Fungsi";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Run the user-defined function '%1'.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://ms.wikipedia.org/wiki/Fungsi";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Run the user-defined function '%1' and use its output.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "dengan:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Hasilkan '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "Buat sesuatu";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "Untuk";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Menghasilkan suatu fungsi tanpa output.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "kembali";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Mencipta satu fungsi dengan pengeluaran.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Amaran: Fungsi ini mempunyai parameter yang berganda.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Serlahkan definisi fungsi";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "If a value is true, then return a second value.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Amaran: Blok ini hanya boleh digunakan dalam fungsi definisi.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "Nama input:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Tambah satu input pada fungsi.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "Input-input";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Tambah, alih keluar atau susun semula input pada fungsi ini.";
Blockly.Msg.PULSEIN = "Pulse In";  // untranslated
Blockly.Msg.PYGMO_BLACK = "Black";  // untranslated
Blockly.Msg.PYGMO_BUTTON = " If button in location ";  // untranslated
Blockly.Msg.PYGMO_BUTTON_EQUAL = " is equal to";  // untranslated
Blockly.Msg.PYGMO_CIRCLE = "Circle";  // untranslated
Blockly.Msg.PYGMO_DERECHO = " right";  // untranslated
Blockly.Msg.PYGMO_DO = "Do";  // untranslated
Blockly.Msg.PYGMO_ElSE = "Else";  // untranslated
Blockly.Msg.PYGMO_FOLLOWER = "Follow line";  // untranslated
Blockly.Msg.PYGMO_FORWARD = "Forward";  // untranslated
Blockly.Msg.PYGMO_HIGH = "High";  // untranslated
Blockly.Msg.PYGMO_INTERSECCION = "If found intersection color  ";  // untranslated
Blockly.Msg.PYGMO_LEFT = "Left";  // untranslated
Blockly.Msg.PYGMO_LIGHTFOLLOWER = "Light Follower -Range ";  // untranslated
Blockly.Msg.PYGMO_LIGHTIF = "If light sensor left";  // untranslated
Blockly.Msg.PYGMO_LOW = "Low";  // untranslated
Blockly.Msg.PYGMO_MAX = "Highest";  // untranslated
Blockly.Msg.PYGMO_MEDIUM = "Medium";  // untranslated
Blockly.Msg.PYGMO_MOVE = "Move";  // untranslated
Blockly.Msg.PYGMO_OBSTACULO = "If there is a obstacle ";  // untranslated
Blockly.Msg.PYGMO_REVERSE = "Reverse";  // untranslated
Blockly.Msg.PYGMO_RIGHT = "Right";  // untranslated
Blockly.Msg.PYGMO_SECONDS = " second(s)";  // untranslated
Blockly.Msg.PYGMO_SKATE = "Snake  ";  // untranslated
Blockly.Msg.PYGMO_SPEED = "Speed";  // untranslated
Blockly.Msg.PYGMO_SPEEDBLOCK = "Motor Speed  left";  // untranslated
Blockly.Msg.PYGMO_STEPS = "Amount of times  ";  // untranslated
Blockly.Msg.PYGMO_STOP = "Stop";  // untranslated
Blockly.Msg.PYGMO_TIME = "Time";  // untranslated
Blockly.Msg.PYGMO_TIMES = " times";  // untranslated
Blockly.Msg.PYGMO_TURN = "Turn ";  // untranslated
Blockly.Msg.PYGMO_WAIT = "Wait";  // untranslated
Blockly.Msg.PYGMO_WHITE = "White";  // untranslated
Blockly.Msg.RACE = "Race";  // untranslated
Blockly.Msg.RANGO = "range";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "Padamkan Komen";
Blockly.Msg.RENAME_VARIABLE = "Tukar nama pembolehubah...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Tukar nama semua pembolehubah '%1' kepada:";
Blockly.Msg.RETURN = "Return";  // untranslated
Blockly.Msg.REVERSE = "REVERSE";  // untranslated
Blockly.Msg.SEGUNDOS = "seconds";  // untranslated
Blockly.Msg.SENSORREAD = "sensor Read";  // untranslated
Blockly.Msg.SERIAL_AVAILABLE = "Bytes available into Serial";  // untranslated
Blockly.Msg.SERIAL_BEGIN = "Serial begin ";  // untranslated
Blockly.Msg.SERIAL_PRINT = "Serial println";  // untranslated
Blockly.Msg.SERIAL_READ = "Read Serial ";  // untranslated
Blockly.Msg.SET = "Set";  // untranslated
Blockly.Msg.SET_UP = "Set_up      ";  // untranslated
Blockly.Msg.SPEED = "speed";  // untranslated
Blockly.Msg.STEPS = "steps";  // untranslated
Blockly.Msg.STRING = "String";  // untranslated
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "append text";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "Untuk";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Append some text to variable '%1'.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "Kepada huruf kecil";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "to Title Case";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "Kepada HURUF BESAR";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Return a copy of the text in a different case.";
Blockly.Msg.TEXT_CHARAT_FIRST = "get first letter";
Blockly.Msg.TEXT_CHARAT_FROM_END = "get letter # from end";
Blockly.Msg.TEXT_CHARAT_FROM_START = "get letter #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "Dalam teks";
Blockly.Msg.TEXT_CHARAT_LAST = "Dapatkan abjad terakhir";
Blockly.Msg.TEXT_CHARAT_RANDOM = "Dapatkan abjad rawak";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Returns the letter at the specified position.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Add an item to the text.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "Sertai";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Add, remove, or reorder sections to reconfigure this text block.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "to letter # from end";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "to letter #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "untuk huruf terakhir";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "dalam teks";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "get substring from first letter";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "get substring from letter # from end";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "get substring from letter #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Returns a specified portion of the text.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "dalam teks";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "mencari kejadian pertama teks";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "mencari kejadian terakhir teks";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Kembalikan Indeks kejadian pertama/terakhir dari teks pertama ke dalam teks kedua.  Kembalikan 0 Jika teks tidak ditemui.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 adalah kosong";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Kembalikan benar jika teks yang disediakan adalah kosong.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "hasilkan teks dengan";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Hasilkan sebahagian teks dengan menghubungkan apa jua nombor item.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "panjang %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Kembalikan jumlah huruf (termasuk ruang) dalam teks yang disediakan.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "cetak %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Cetak teks yang ditentukan, nombor atau nilai lain.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Peringatan kepada pengguna untuk nombor.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Peringatkan pengguna untuk sebahagian teks.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "Prom untuk nombor dengan mesej";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "Prom untuk teks dengan mesej";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://ms.wikipedia.org/wiki/Rentetan";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Huruf, perkataan, atau baris teks.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "mengurangkan kawasan dari kedua-dua belah";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "mengurangkan ruang dari sebelah kiri";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "mengurangkan kawasan dari sisi kanan";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Kembali salinan teks dengan ruang yang dikeluarkan daripada satu atau hujung kedua belah.";
Blockly.Msg.TO = "to";  // untranslated
Blockly.Msg.TODAY = "Hari ini";
Blockly.Msg.TONE = "Tone";  // untranslated
Blockly.Msg.TOOLTIP_ANALOGREAD = "Check the analog pin'state";  // untranslated
Blockly.Msg.TOOLTIP_ANALOGWRITE = "Write in a analog pin";  // untranslated
Blockly.Msg.TOOLTIP_BOOLEAN = "Write true/false";  // untranslated
Blockly.Msg.TOOLTIP_CHAR = "Write only one character";  // untranslated
Blockly.Msg.TOOLTIP_COMENTARIO = "Write a comment";  // untranslated
Blockly.Msg.TOOLTIP_COUNTERDECLARATION = "Declare one counter";  // untranslated
Blockly.Msg.TOOLTIP_DECLARARVECTOR = "Write the vector's length";  // untranslated
Blockly.Msg.TOOLTIP_DECRCOUNTER = "Decrement variable'value";  // untranslated
Blockly.Msg.TOOLTIP_DELAY = "Pause the program for a determinated time (ms)";  // untranslated
Blockly.Msg.TOOLTIP_DIGITALREAD = "Check the digital pin'state";  // untranslated
Blockly.Msg.TOOLTIP_DIGITALWRITE = "Write in a digital pin  HIGH or LOW";  // untranslated
Blockly.Msg.TOOLTIP_ESPECIALCODIGO = "Press over the space to write a code manually";  // untranslated
Blockly.Msg.TOOLTIP_FUNCIONCONRETURN = "Declare one function whit return.Press over icon to add arguments";  // untranslated
Blockly.Msg.TOOLTIP_FUNCIONSINRETURN = "Declare one function whithout return.Press over icon to add arguments";  // untranslated
Blockly.Msg.TOOLTIP_GETFUNCTION = "Use a determinated function whit return, which was declarated formerly";  // untranslated
Blockly.Msg.TOOLTIP_GETVAR = "Invoke variable";  // untranslated
Blockly.Msg.TOOLTIP_GETVECTOR = "Write the position where you want to get the stored value";  // untranslated
Blockly.Msg.TOOLTIP_GOFORWARD = "Turn on two motors forward";  // untranslated
Blockly.Msg.TOOLTIP_GOREVERSE = "Turn off two motors backward";  // untranslated
Blockly.Msg.TOOLTIP_INCRCOUNTER = "Increase variable'value";  // untranslated
Blockly.Msg.TOOLTIP_INICIALIZARVECTOR = "Write the vector's initial values. Press over button to add more arguments";  // untranslated
Blockly.Msg.TOOLTIP_KEYBOARDBEGIN = "Send a key";  // untranslated
Blockly.Msg.TOOLTIP_KEYBOARDINIT = "Initialize keyboard mode";  // untranslated
Blockly.Msg.TOOLTIP_LIBRERIA = "Declare some library that you want to use.";  // untranslated
Blockly.Msg.TOOLTIP_LINEACODIGO = "Use this block to write one code line manually";  // untranslated
Blockly.Msg.TOOLTIP_LINECOMPARE = "Set line sensor' threshold, to choose between white or black";  // untranslated
Blockly.Msg.TOOLTIP_LINEREAD = "Check line sensor' state";  // untranslated
Blockly.Msg.TOOLTIP_MOTOROFF = "Turn off one motor";  // untranslated
Blockly.Msg.TOOLTIP_MOTORON = "Turn on one motor";  // untranslated
Blockly.Msg.TOOLTIP_MOTORSOFF = "Turn off two motors";  // untranslated
Blockly.Msg.TOOLTIP_MOTORSPEED = "Change the motor'speed with a value between";  // untranslated
Blockly.Msg.TOOLTIP_MOUSEINIT = "Initialize mouse mode";  // untranslated
Blockly.Msg.TOOLTIP_MOUSEMOVE = "Send coordinates to move mouse";  // untranslated
Blockly.Msg.TOOLTIP_NOTONE = "Turn off a tone, which was generated formerly";  // untranslated
Blockly.Msg.TOOLTIP_NUMERICVAR = "Use a numeric value";  // untranslated
Blockly.Msg.TOOLTIP_PARAMETRO = "Add some argument to your functions";  // untranslated
Blockly.Msg.TOOLTIP_PINMODE = "Set behavior of a pin Input/Output";  // untranslated
Blockly.Msg.TOOLTIP_SENSORREAD = "Check line sensor' analog state";  // untranslated
Blockly.Msg.TOOLTIP_SERIALAVAILABLE = "Get the number of bytes available for reading";  // untranslated
Blockly.Msg.TOOLTIP_SERIALBEGIN = "Initialize the serial communication";  // untranslated
Blockly.Msg.TOOLTIP_SERIALPRINT = "Send a determinated value through serial communication";  // untranslated
Blockly.Msg.TOOLTIP_SERIALREAD = "Read the first byte available";  // untranslated
Blockly.Msg.TOOLTIP_SETFUNCTION = "Use a determinated function whitout return, which was declarated formerly";  // untranslated
Blockly.Msg.TOOLTIP_SETVAR = "Modify a varible'value";  // untranslated
Blockly.Msg.TOOLTIP_SETVECTOR = "Write the position and the value which you want to store";  // untranslated
Blockly.Msg.TOOLTIP_STRINGVAR = "Write a String/text";  // untranslated
Blockly.Msg.TOOLTIP_TONE = "Generate a tone in a determinated pin and frecuency";  // untranslated
Blockly.Msg.TOOLTIP_TURNGHT = "first motor is on the left and the second is on the right";  // untranslated
Blockly.Msg.TOOLTIP_TURNLEFT = "first motor is on the left and the second is on the right";  // untranslated
Blockly.Msg.TOOLTIP_ULTRASOUNDREAD = "Check the ultra sound sensor";  // untranslated
Blockly.Msg.TOOLTIP_VARDECLARATION = "Declare one variable";  // untranslated
Blockly.Msg.TOOTTIP_CIRCLE = "Choose velocity, direction and time";  // untranslated
Blockly.Msg.TURNOFF = "Turn off";  // untranslated
Blockly.Msg.TURN_LEFT = "turn Left";  // untranslated
Blockly.Msg.TURN_RIGHT = "turn Right";  // untranslated
Blockly.Msg.TYPE = "type";  // untranslated
Blockly.Msg.ULTRASOUNDREAD = "ultrasound Read";  // untranslated
Blockly.Msg.VALUE = "value";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "Perkara";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Hasilkan 'set %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Kembalikan nilai pemboleh ubah ini.";
Blockly.Msg.VARIABLES_SET = "set %1 ke %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Hasilkan 'set %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Set pembolehubah ini supaya sama dengan input.";
Blockly.Msg.WHEEL = "wheel";  // untranslated
Blockly.Msg.WHITE = "WHITE";  // untranslated
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;