// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.sk');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_ARG = "Add Argument";  // untranslated
Blockly.Msg.ADD_ARGS = "Add Arguments";  // untranslated
Blockly.Msg.ADD_COMMENT = "Pridať komentár";
Blockly.Msg.ANALOG_READ = "analog Read";  // untranslated
Blockly.Msg.ANALOG_WRITE = "analog Write";  // untranslated
Blockly.Msg.ANGLE = " angle";  // untranslated
Blockly.Msg.ARCOIRIS = "Rainbow";  // untranslated
Blockly.Msg.AUTH = "Autorizujte prosím túto aplikáciu, aby ste mohli uložiť a zdieľať vašu prácu.";
Blockly.Msg.BLACK = "BLACK";  // untranslated
Blockly.Msg.BLINK = "Blink ";  // untranslated
Blockly.Msg.BOOLEAN = "boolean";  // untranslated
Blockly.Msg.BOOLEANO = "Boolean";  // untranslated
Blockly.Msg.BY = "by";  // untranslated
Blockly.Msg.CHANGE_VALUE_TITLE = "Zmeniť hodnotu:";
Blockly.Msg.CHAR = "Character";  // untranslated
Blockly.Msg.CHAT = "Písaním do tohto políčka komunikujte so spolupracovníkmi!";
Blockly.Msg.CLEAN_UP = "Clean up Blocks";  // untranslated
Blockly.Msg.CLICKDER = "Right_Click";  // untranslated
Blockly.Msg.CLICKIZQ = "Left_Click";  // untranslated
Blockly.Msg.CLICKMID = "Middle_Click";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "Zvinúť bloky";
Blockly.Msg.COLLAPSE_BLOCK = "Zvinúť blok";
Blockly.Msg.COLOR = " colour";  // untranslated
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "farba 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "farba 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "pomer";
Blockly.Msg.COLOUR_BLEND_TITLE = "zmiešať";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Zmieša dve farby v danom pomere (0.0 - 1.0).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://en.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Zvoľte farbu z palety.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "náhodná farba";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Zvoliť farbu náhodne.";
Blockly.Msg.COLOUR_RGB_BLUE = "modrá";
Blockly.Msg.COLOUR_RGB_GREEN = "zelená";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "červená";
Blockly.Msg.COLOUR_RGB_TITLE = "ofarbiť s";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Vytvoriť farbu pomocou zadaného množstva červenej, zelenej a modrej. Množstvo musí byť medzi 0 a 100.";
Blockly.Msg.COMENTARIO = "Comment";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "opustiť slučku";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "prejdi na nasledujúce opakovanie slučky";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Opustiť túto slučku.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Vynechať zvyšok tejto slučky a pokračovať ďalším opakovaním.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Upozornenie: Tento blok sa môže používať len v rámci slučky.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "pre každý prvok %1 v zozname %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Pre každý prvok v zozname priraď jeho hodnotu do premenej '%1' a vykonaj príkazy.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "počítať s %1 od %2 do %3 o %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Nechá premennú '%1' nadobúdať hodnoty od začiatočného čísla po konečné s daným medzikrokom a vykoná zadané bloky.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Pridať podmienku k \"ak\" bloku.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Pridať poslednú záchytnú podmienku k \"ak\" bloku.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Pridať, odstrániť alebo zmeniť poradie oddielov tohto \"ak\" bloku.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "inak";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "inak ak";
Blockly.Msg.CONTROLS_IF_MSG_IF = "ak";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Ak je hodnota pravda, vykonaj príkazy.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Ak je hodnota pravda, vykonaj príkazy v prvom bloku. Inak vykonaj príkazy v druhom bloku.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Ak je prvá hodnota pravda, vykonaj príkazy v prvom bloku. Inak, ak je druhá hodnota pravda, vykonaj príkazy v druhom bloku.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Ak je prvá hodnota pravda, vykonaj príkazy v prvom bloku. Inak, ak je druhá hodnota pravda, vykonaj príkazy v druhom bloku. Ak ani jedna hodnota nie je pravda, vykonaj príkazy v poslednom bloku.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "rob";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "opakuj %1 krát";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Opakuj určité príkazy viackrát.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "opakuj kým nebude";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "opakuj kým";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Kým je hodnota nepravdivá, vykonávaj príkazy.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Kým je hodnota pravdivá, vykonávaj príkazy.";
Blockly.Msg.COUNTER = "Counter";  // untranslated
Blockly.Msg.CUMPLEANOS = "Birthday";  // untranslated
Blockly.Msg.DECLARACIONES = "Statements";  // untranslated
Blockly.Msg.DECR_CONT = "Decrement";  // untranslated
Blockly.Msg.DELAY = "Delay";  // untranslated
Blockly.Msg.DELETE_BLOCK = "Odstrániť blok";
Blockly.Msg.DELETE_X_BLOCKS = "Odstrániť %1 blokov";
Blockly.Msg.DER = "RT";  // untranslated
Blockly.Msg.DIFFERENTTO = "Different to";  // untranslated
Blockly.Msg.DIGITAL_READ = "digital Read";  // untranslated
Blockly.Msg.DIGITAL_WRITE = "digital Write";  // untranslated
Blockly.Msg.DIRECCION = "direction";  // untranslated
Blockly.Msg.DISABLE_BLOCK = "Vypnúť blok";
Blockly.Msg.DISTANCE = "distance";  // untranslated
Blockly.Msg.DUPLICATE_BLOCK = "Duplikovať";
Blockly.Msg.DURACION = "duration";  // untranslated
Blockly.Msg.EJE_X = "axis x";  // untranslated
Blockly.Msg.EJE_Y = "axis y";  // untranslated
Blockly.Msg.ENABLE_BLOCK = "Povoliť blok";
Blockly.Msg.EQUALTO = "Equal to";  // untranslated
Blockly.Msg.EXPAND_ALL = "Rozvinúť bloky";
Blockly.Msg.EXPAND_BLOCK = "Rozvinúť blok";
Blockly.Msg.EXTERNAL_INPUTS = "Vonkajšie vstupy";
Blockly.Msg.FIN_CODE_PYGMO = "       End";  // untranslated
Blockly.Msg.FLOAT = "float";  // untranslated
Blockly.Msg.FOR = "Count with";  // untranslated
Blockly.Msg.FOREVER = "Forever                                  ";  // untranslated
Blockly.Msg.FORWARD = "FORWARD";  // untranslated
Blockly.Msg.FRECUENCY = "frecuency";  // untranslated
Blockly.Msg.FROM = "from";  // untranslated
Blockly.Msg.FUNCTION = "Function";  // untranslated
Blockly.Msg.FUNCTIONWIHTRETURN = "Return Function";  // untranslated
Blockly.Msg.GOFORWARD = "go Forward ";  // untranslated
Blockly.Msg.GOREVERSE = "go Reverse ";  // untranslated
Blockly.Msg.GREATEROREQUAL = "Grater or Equal to";  // untranslated
Blockly.Msg.GREATERTHAN = "Greater than";  // untranslated
Blockly.Msg.HELP = "Pomoc";
Blockly.Msg.HIGH = "HIGH";  // untranslated
Blockly.Msg.INCR_CONT = "Increase";  // untranslated
Blockly.Msg.INICIO_CODE = "Starting program";  // untranslated
Blockly.Msg.INLINE_INPUTS = "Riadkové vstupy";
Blockly.Msg.INPUT = "INPUT";  // untranslated
Blockly.Msg.INPUT_PULLUP = "INPUT_PULLUP";  // untranslated
Blockly.Msg.INT = "int";  // untranslated
Blockly.Msg.INVERTIR = "Reverse motion";  // untranslated
Blockly.Msg.IZQ = "LFT";  // untranslated
Blockly.Msg.KEYBOARD_BEGIN = "Keyboard begin";  // untranslated
Blockly.Msg.KEYBOARD_PRINT = "Keyboard print";  // untranslated
Blockly.Msg.KEYBOARD_TEXT = "Write one key";  // untranslated
Blockly.Msg.LEDOFF = "LED Off";  // untranslated
Blockly.Msg.LEDON = "LED On";  // untranslated
Blockly.Msg.LENGTH = "length";  // untranslated
Blockly.Msg.LESSOEQUAL = "Less or Equal to";  // untranslated
Blockly.Msg.LESSTHAN = "Less than";  // untranslated
Blockly.Msg.LIBRERIA = "Library";  // untranslated
Blockly.Msg.LIBRERIA_TEXT = "Write the Library'name";  // untranslated
Blockly.Msg.LINEA_CODIGO = "Line Code";  // untranslated
Blockly.Msg.LINECOMPARE = "line Compare";  // untranslated
Blockly.Msg.LINEREAD = "line Read";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "prázdny zoznam";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Vráti zoznam nulovej dĺžky, ktorý neobsahuje žiadne prvky.";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "zoznam";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Pridaj, odstráň alebo zmeň poradie v tomto zoznamovom bloku.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "vytvor zoznam s";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Pridaj prvok do zoznamu.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Vytvor zoznam s ľubovoľným počtom prvkov.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "prvý";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# od konca";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET = "zisti";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "zisti a odstráň";
Blockly.Msg.LISTS_GET_INDEX_LAST = "posledný";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "náhodný";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "odstráň";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Vráti počiatočný prvok zoznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Vráti prvok na určenej pozícii v zozname. #1 je posledný prvok.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Vráti prvok na určenej pozícii v zozname. #1 je počiatočný prvok.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Vráti posledný prvok zoznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Vráti náhodný prvok zoznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Odstráni a vráti prvý prvok v zozname.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Odstráni a vráti prvok z určenej pozície v zozname. #1 je posledný prvok.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Odstráni a vráti prvok z určenej pozície v zozname. #1 je prvý prvok.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Odstráni a vráti posledný prvok v zozname.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Odstráni a vráti náhodný prvok v zozname.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Odstráni prvý prvok v zozname.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Odstráni prvok na určenej pozícii v zozname. #1 je posledný prvok.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Odstráni prvok na určenej pozícii v zozname. #1 je prvý prvok.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Odstráni posledný prvok v zozname.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Odstráni náhodný prvok v zozname.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "po # od konca";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "po #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "po koniec";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "Získať podzoznam od začiatku";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "Získať podzoznam od # od konca";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "získať podzoznam od #";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Skopíruje určený úsek zoznamu.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "nájdi prvý výskyt prvku";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "nájdi posledný výskyt prvku";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Vráti index prvého/posledného výskytu prvku v zozname. Ak nenašiel, vráti 0.";
Blockly.Msg.LISTS_INLIST = "v zozname";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 je prázdny";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Vráti pravda, ak je zoznam prázdny.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "dĺžka %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Vráti dĺžku zoznamu";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "vytvor zoznam s prvkom %1 opakovaným %2 krát";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Vytvorí zoznam s niekoľkými rovnakými prvkami s danou hodnotou.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "ako";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "vložiť na";
Blockly.Msg.LISTS_SET_INDEX_SET = "nastaviť";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Vsunie prvok na začiatok zoznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Vsunie prvok na určenú pozíciu v zozname. #1 je posledný prvok.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Vsunie prvok na určenú pozíciu v zozname. #1 je prvý prvok.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Pripojí prvok na koniec zoznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Vsunie prvok na náhodné miesto v zozname.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Nastaví prvý prvok v zozname.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Nastaví prvok na určenej pozícii v zozname. #1 je posledný prvok.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Nastaví prvok na určenej pozícii v zozname. #1 je prvý prvok.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Nastaví posledný prvok v zozname.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Nastaví posledný prvok v zozname.";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "vytvoriť zoznam z textu";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "vytvoriť text zo zoznamu";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Spojiť zoznam textov do jedného textu s oddeľovačmi.";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Rozdelenie textu do zoznamu textov, lámanie na oddeľovačoch.";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "s oddeľovačom";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "nepravda";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Vráť buď hodnotu pravda alebo nepravda.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "pravda";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Vráť hodnotu pravda, ak sú vstupy rovnaké.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Vráť hodnotu pravda ak prvý vstup je väčší než druhý.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Vráť hodnotu pravda ak prvý vstup je väčší alebo rovný druhému.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Vráť hodnotu pravda, ak prvý vstup je menší než druhý.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Vráť hodnotu pravda ak prvý vstup je menší alebo rovný druhému.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Vráť hodnotu pravda, ak vstupy nie sú rovnaké.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "nie je %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Vráti hodnotu pravda, ak je vstup nepravda. Vráti hodnotu nepravda ak je vstup pravda.";
Blockly.Msg.LOGIC_NULL = "nič";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Vráti hodnotu nula.";
Blockly.Msg.LOGIC_OPERATION_AND = "a";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "alebo";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Vráť hodnotu pravda, ak sú vstupy pravdivé.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Vráť hodnotu pravda, ak je aspoň jeden vstup pravda.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "ak nepravda";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "ak pravda";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Skontroluj podmienku testom. Ak je podmienka pravda, vráť hodnotu \"ak pravda\", inak vráť hodnotu \"ak nepravda\".";
Blockly.Msg.LOOP = "Loop         ";  // untranslated
Blockly.Msg.LOW = "LOW";  // untranslated
Blockly.Msg.LUZ = "light";  // untranslated
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Vráť súčet dvoch čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Vráť podiel dvoch čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Vráť rozdiel dvoch čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Vráť súčin dvoch čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Vráť prvé číslo umocnené druhým.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_TITLE = "zmeniť %1 o %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Pridaj číslo do premennej \"%1\".";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant‎";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Vráť jednu zo zvyčajných konštánt: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), alebo ∞ (nekonečno).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "obmedz %1 od %2 do %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Obmedzí číslo do zadaných hraníc (vrátane).";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "je deliteľné";
Blockly.Msg.MATH_IS_EVEN = "je párne";
Blockly.Msg.MATH_IS_NEGATIVE = "je záporné";
Blockly.Msg.MATH_IS_ODD = "je nepárne";
Blockly.Msg.MATH_IS_POSITIVE = "je kladné";
Blockly.Msg.MATH_IS_PRIME = "je prvočíslo";
Blockly.Msg.MATH_IS_TOOLTIP = "Skontroluj či je číslo párne, nepárne, celé, kladné, záporné alebo deliteľné určitým číslom. Vráť hodnotu pravda alebo nepravda.";
Blockly.Msg.MATH_IS_WHOLE = "je celé číslo";
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_TITLE = "zvyšok po delení %1 + %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Vráť zvyšok po delení jedného čísla druhým.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Číslo.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "priemer zoznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "najväčšie v zozname";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "medián zoznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "najmenšie v zozname";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "najčastejšie v zozname";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "náhodný prvok zoznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "smerodajná odchýlka zoznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "súčet zoznamu";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Vráť aritmetický priemer čísel v zozname.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Vrátiť najväčšie číslo v zozname.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Vráť medián čísel v zozname.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Vrátiť najmenšie číslo v zozname.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Vrátiť najčastejší prvok v zozname.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Vráť náhodne zvolený prvok zoznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Vráť smeroddajnú odchýlku zoznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Vráť súčet všetkých čísel v zozname.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "náhodné číslo od 0 do 1";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Vráť náhodné číslo z intervalu 0.0 (vrátane) až 1.0.";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "náhodné celé číslo od %1 do %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Vráť náhodné celé číslo z určeného intervalu (vrátane).";
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "zaokrúhli";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "zaokrúhli nadol";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "zaokrúhli nahor";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Zaokrúhli číslo nahor alebo nadol.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "absolútna hodnota";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "druhá odmocnina";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Vráť absolútnu hodnotu čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Vráť e umocnené číslom.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Vráť prirodzený logaritmus čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Vráť logaritmus čísla so základom 10.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Vráť opačné číslo.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Vráť 10 umocnené číslom.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Vráť druhú odmocninu čísla.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Vráť arkus kosínus čísla.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Vráť arkus sínus čísla.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Vráť arkus tangens čísla.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Vráť kosínus uhla (v stupňoch).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Vráť sínus uhla (v stupňoch).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Vráť tangens uhla (v stupňoch).";
Blockly.Msg.ME = "Ja";
Blockly.Msg.MICROSEGUNDOS = "microseconds";  // untranslated
Blockly.Msg.MILISEGUNDOS = "miliseconds";  // untranslated
Blockly.Msg.MILLIS = "Elapsed milliseconds";  // untranslated
Blockly.Msg.MODE = "mode";  // untranslated
Blockly.Msg.MOTORS_OFF = "motors Off ";  // untranslated
Blockly.Msg.MOTOR_OFF = "motor Off";  // untranslated
Blockly.Msg.MOTOR_ON = "motor On";  // untranslated
Blockly.Msg.MOTOR_SPEED = "motor Speed";  // untranslated
Blockly.Msg.MOUSE_BEGIN = "Mouse begin";  // untranslated
Blockly.Msg.MOUSE_MOVE = "Mouse move";  // untranslated
Blockly.Msg.NAMEINIT = "name";  // untranslated
Blockly.Msg.NAVIDAD = "Christmas";  // untranslated
Blockly.Msg.NEW_VARIABLE = "Nová premenná...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Názov novej premennej:";
Blockly.Msg.NOTA = "note";  // untranslated
Blockly.Msg.NO_TONE = "No tone";  // untranslated
Blockly.Msg.NUMERIC = "Number";  // untranslated
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.OUTPUT = "OUTPUT";  // untranslated
Blockly.Msg.OWNCODE = "Write your own code";  // untranslated
Blockly.Msg.PINMODE = "pin Mode";  // untranslated
Blockly.Msg.PIROGAMES = "Pyrotechnic Games";  // untranslated
Blockly.Msg.POLICIA = "Police";  // untranslated
Blockly.Msg.PORT = " port";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "povoliť príkazy";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "s:";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Spustí používateľom definovanú funkciu '%1'.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Spustí používateľom definovanú funkciu '%1' a použije jej výstup.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "s:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Vytvoriť '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "urob niečo";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "na";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Vytvorí funciu bez výstupu.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "vrátiť";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Vytvorí funkciu s výstupom.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Upozornenie: Táto funkcia má duplicitné parametre.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Zvýrazniť definíciu funkcie";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Ak je hodnota pravda, tak vráti druhú hodnotu.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Upozornenie: Tento blok môže byť len vo vnútri funkcie.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "názov vstupu:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Pridať vstup do funkcie.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "vstupy";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Pridať, odstrániť alebo zmeniť poradie vstupov tejto funkcie.";
Blockly.Msg.PULSEIN = "Pulse In";  // untranslated
Blockly.Msg.PYGMO_BLACK = "Black";  // untranslated
Blockly.Msg.PYGMO_BUTTON = " If button in location ";  // untranslated
Blockly.Msg.PYGMO_BUTTON_EQUAL = " is equal to";  // untranslated
Blockly.Msg.PYGMO_CIRCLE = "Circle";  // untranslated
Blockly.Msg.PYGMO_DERECHO = " right";  // untranslated
Blockly.Msg.PYGMO_DO = "Do";  // untranslated
Blockly.Msg.PYGMO_ElSE = "Else";  // untranslated
Blockly.Msg.PYGMO_FOLLOWER = "Follow line";  // untranslated
Blockly.Msg.PYGMO_FORWARD = "Forward";  // untranslated
Blockly.Msg.PYGMO_HIGH = "High";  // untranslated
Blockly.Msg.PYGMO_INTERSECCION = "If found intersection color  ";  // untranslated
Blockly.Msg.PYGMO_LEFT = "Left";  // untranslated
Blockly.Msg.PYGMO_LIGHTFOLLOWER = "Light Follower -Range ";  // untranslated
Blockly.Msg.PYGMO_LIGHTIF = "If light sensor left";  // untranslated
Blockly.Msg.PYGMO_LOW = "Low";  // untranslated
Blockly.Msg.PYGMO_MAX = "Highest";  // untranslated
Blockly.Msg.PYGMO_MEDIUM = "Medium";  // untranslated
Blockly.Msg.PYGMO_MOVE = "Move";  // untranslated
Blockly.Msg.PYGMO_OBSTACULO = "If there is a obstacle ";  // untranslated
Blockly.Msg.PYGMO_REVERSE = "Reverse";  // untranslated
Blockly.Msg.PYGMO_RIGHT = "Right";  // untranslated
Blockly.Msg.PYGMO_SECONDS = " second(s)";  // untranslated
Blockly.Msg.PYGMO_SKATE = "Snake  ";  // untranslated
Blockly.Msg.PYGMO_SPEED = "Speed";  // untranslated
Blockly.Msg.PYGMO_SPEEDBLOCK = "Motor Speed  left";  // untranslated
Blockly.Msg.PYGMO_STEPS = "Amount of times  ";  // untranslated
Blockly.Msg.PYGMO_STOP = "Stop";  // untranslated
Blockly.Msg.PYGMO_TIME = "Time";  // untranslated
Blockly.Msg.PYGMO_TIMES = " times";  // untranslated
Blockly.Msg.PYGMO_TURN = "Turn ";  // untranslated
Blockly.Msg.PYGMO_WAIT = "Wait";  // untranslated
Blockly.Msg.PYGMO_WHITE = "White";  // untranslated
Blockly.Msg.RACE = "Race";  // untranslated
Blockly.Msg.RANGO = "range";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "Odstrániť komentár";
Blockly.Msg.RENAME_VARIABLE = "Premenovať premennú...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Premenovať všetky premenné '%1' na:";
Blockly.Msg.RETURN = "Return";  // untranslated
Blockly.Msg.REVERSE = "REVERSE";  // untranslated
Blockly.Msg.SEGUNDOS = "seconds";  // untranslated
Blockly.Msg.SENSORREAD = "sensor Read";  // untranslated
Blockly.Msg.SERIAL_AVAILABLE = "Bytes available into Serial";  // untranslated
Blockly.Msg.SERIAL_BEGIN = "Serial begin ";  // untranslated
Blockly.Msg.SERIAL_PRINT = "Serial println";  // untranslated
Blockly.Msg.SERIAL_READ = "Read Serial ";  // untranslated
Blockly.Msg.SET = "Set";  // untranslated
Blockly.Msg.SET_UP = "Set_up      ";  // untranslated
Blockly.Msg.SPEED = "speed";  // untranslated
Blockly.Msg.STEPS = "steps";  // untranslated
Blockly.Msg.STRING = "String";  // untranslated
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "pridaj text";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "do";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Pridaj určitý text do premennej '%1'.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "na malé písmená";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "na Veľké Začiatočné Písmená";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "na VEĽKÉ PÍSMENÁ";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Vráť kópiu textu s inou veľkosťou písmen.";
Blockly.Msg.TEXT_CHARAT_FIRST = "zisti prvé písmeno";
Blockly.Msg.TEXT_CHARAT_FROM_END = "zisti # písmeno od konca";
Blockly.Msg.TEXT_CHARAT_FROM_START = "zisti písmeno #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "v texte";
Blockly.Msg.TEXT_CHARAT_LAST = "zisti posledné písmeno";
Blockly.Msg.TEXT_CHARAT_RANDOM = "vyber náhodné písmeno";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Vráti písmeno na určenej pozícii.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Pridaj prvok do textu.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "spoj";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Pridaj, odstráň alebo zmeň poradie oddielov v tomto textovom bloku.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "po # písmeno od konca";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "po písmeno #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "po koniec";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "v texte";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "vyber podreťazec od začiatku";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "vyber podreťazec od # písmena od konca";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "vyber podreťazec od písmena #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Vráti určenú časť textu.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "v texte";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "nájdi prvý výskyt textu";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "nájdi posledný výskyt textu";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Vráti index prvého/posledného výskytu prvého textu v druhom texte. Ak nenájde, vráti 0.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 je prázdny";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Vráti hodnotu pravda, ak zadaný text je prázdny.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "vytvor text z";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Vytvor text spojením určitého počtu prvkov.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "dĺžka %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Vráti počet písmen (s medzerami) v zadanom texte.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "píš %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Napíš zadaný text, číslo alebo hodnotu.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Výzva pre používateľa na zadanie čísla.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Výzva pre používateľa na zadanie textu.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "výzva na zadanie čísla so správou";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "výzva za zadanie textu so správou";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Písmeno, slovo alebo riadok textu.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "odstráň medzery z oboch strán";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "odstráň medzery z ľavej strany";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "odstráň medzery z pravej strany";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Vráť kópiu textu bez medzier na jednom alebo oboch koncoch.";
Blockly.Msg.TO = "to";  // untranslated
Blockly.Msg.TODAY = "Dnes";
Blockly.Msg.TONE = "Tone";  // untranslated
Blockly.Msg.TOOLTIP_ANALOGREAD = "Check the analog pin'state";  // untranslated
Blockly.Msg.TOOLTIP_ANALOGWRITE = "Write in a analog pin";  // untranslated
Blockly.Msg.TOOLTIP_BOOLEAN = "Write true/false";  // untranslated
Blockly.Msg.TOOLTIP_CHAR = "Write only one character";  // untranslated
Blockly.Msg.TOOLTIP_COMENTARIO = "Write a comment";  // untranslated
Blockly.Msg.TOOLTIP_COUNTERDECLARATION = "Declare one counter";  // untranslated
Blockly.Msg.TOOLTIP_DECLARARVECTOR = "Write the vector's length";  // untranslated
Blockly.Msg.TOOLTIP_DECRCOUNTER = "Decrement variable'value";  // untranslated
Blockly.Msg.TOOLTIP_DELAY = "Pause the program for a determinated time (ms)";  // untranslated
Blockly.Msg.TOOLTIP_DIGITALREAD = "Check the digital pin'state";  // untranslated
Blockly.Msg.TOOLTIP_DIGITALWRITE = "Write in a digital pin  HIGH or LOW";  // untranslated
Blockly.Msg.TOOLTIP_ESPECIALCODIGO = "Press over the space to write a code manually";  // untranslated
Blockly.Msg.TOOLTIP_FUNCIONCONRETURN = "Declare one function whit return.Press over icon to add arguments";  // untranslated
Blockly.Msg.TOOLTIP_FUNCIONSINRETURN = "Declare one function whithout return.Press over icon to add arguments";  // untranslated
Blockly.Msg.TOOLTIP_GETFUNCTION = "Use a determinated function whit return, which was declarated formerly";  // untranslated
Blockly.Msg.TOOLTIP_GETVAR = "Invoke variable";  // untranslated
Blockly.Msg.TOOLTIP_GETVECTOR = "Write the position where you want to get the stored value";  // untranslated
Blockly.Msg.TOOLTIP_GOFORWARD = "Turn on two motors forward";  // untranslated
Blockly.Msg.TOOLTIP_GOREVERSE = "Turn off two motors backward";  // untranslated
Blockly.Msg.TOOLTIP_INCRCOUNTER = "Increase variable'value";  // untranslated
Blockly.Msg.TOOLTIP_INICIALIZARVECTOR = "Write the vector's initial values. Press over button to add more arguments";  // untranslated
Blockly.Msg.TOOLTIP_KEYBOARDBEGIN = "Send a key";  // untranslated
Blockly.Msg.TOOLTIP_KEYBOARDINIT = "Initialize keyboard mode";  // untranslated
Blockly.Msg.TOOLTIP_LIBRERIA = "Declare some library that you want to use.";  // untranslated
Blockly.Msg.TOOLTIP_LINEACODIGO = "Use this block to write one code line manually";  // untranslated
Blockly.Msg.TOOLTIP_LINECOMPARE = "Set line sensor' threshold, to choose between white or black";  // untranslated
Blockly.Msg.TOOLTIP_LINEREAD = "Check line sensor' state";  // untranslated
Blockly.Msg.TOOLTIP_MOTOROFF = "Turn off one motor";  // untranslated
Blockly.Msg.TOOLTIP_MOTORON = "Turn on one motor";  // untranslated
Blockly.Msg.TOOLTIP_MOTORSOFF = "Turn off two motors";  // untranslated
Blockly.Msg.TOOLTIP_MOTORSPEED = "Change the motor'speed with a value between";  // untranslated
Blockly.Msg.TOOLTIP_MOUSEINIT = "Initialize mouse mode";  // untranslated
Blockly.Msg.TOOLTIP_MOUSEMOVE = "Send coordinates to move mouse";  // untranslated
Blockly.Msg.TOOLTIP_NOTONE = "Turn off a tone, which was generated formerly";  // untranslated
Blockly.Msg.TOOLTIP_NUMERICVAR = "Use a numeric value";  // untranslated
Blockly.Msg.TOOLTIP_PARAMETRO = "Add some argument to your functions";  // untranslated
Blockly.Msg.TOOLTIP_PINMODE = "Set behavior of a pin Input/Output";  // untranslated
Blockly.Msg.TOOLTIP_SENSORREAD = "Check line sensor' analog state";  // untranslated
Blockly.Msg.TOOLTIP_SERIALAVAILABLE = "Get the number of bytes available for reading";  // untranslated
Blockly.Msg.TOOLTIP_SERIALBEGIN = "Initialize the serial communication";  // untranslated
Blockly.Msg.TOOLTIP_SERIALPRINT = "Send a determinated value through serial communication";  // untranslated
Blockly.Msg.TOOLTIP_SERIALREAD = "Read the first byte available";  // untranslated
Blockly.Msg.TOOLTIP_SETFUNCTION = "Use a determinated function whitout return, which was declarated formerly";  // untranslated
Blockly.Msg.TOOLTIP_SETVAR = "Modify a varible'value";  // untranslated
Blockly.Msg.TOOLTIP_SETVECTOR = "Write the position and the value which you want to store";  // untranslated
Blockly.Msg.TOOLTIP_STRINGVAR = "Write a String/text";  // untranslated
Blockly.Msg.TOOLTIP_TONE = "Generate a tone in a determinated pin and frecuency";  // untranslated
Blockly.Msg.TOOLTIP_TURNGHT = "first motor is on the left and the second is on the right";  // untranslated
Blockly.Msg.TOOLTIP_TURNLEFT = "first motor is on the left and the second is on the right";  // untranslated
Blockly.Msg.TOOLTIP_ULTRASOUNDREAD = "Check the ultra sound sensor";  // untranslated
Blockly.Msg.TOOLTIP_VARDECLARATION = "Declare one variable";  // untranslated
Blockly.Msg.TOOTTIP_CIRCLE = "Choose velocity, direction and time";  // untranslated
Blockly.Msg.TURNOFF = "Turn off";  // untranslated
Blockly.Msg.TURN_LEFT = "turn Left";  // untranslated
Blockly.Msg.TURN_RIGHT = "turn Right";  // untranslated
Blockly.Msg.TYPE = "type";  // untranslated
Blockly.Msg.ULTRASOUNDREAD = "ultrasound Read";  // untranslated
Blockly.Msg.VALUE = "value";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "prvok";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Vytvoriť \"nastaviť %1\"";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Vráti hodnotu tejto premennej.";
Blockly.Msg.VARIABLES_SET = "nastaviť %1 na %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Vytvoriť \"získať %1\"";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Nastaví túto premennú, aby sa rovnala vstupu.";
Blockly.Msg.WHEEL = "wheel";  // untranslated
Blockly.Msg.WHITE = "WHITE";  // untranslated
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;